version: '3'

services:
    web:
        build: "./build/web"
        container_name: "web"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./volume:/var/www/html/"
